colsample_bytree: [0.5, 1.0]
colsample_bylevel: [0.5, 1.0]
colsample_bynode: [0.5, 1.0]
learning_rate: [0.00001, 0.9]
max_depth: [4, 15]
n_estimators: [40, 400]
subsample: [0.5, 1.0]
min_child_weight: [2.0, 20.0]
reg_alpha: [0.001, 100.0]
reg_lambda: [0.001, 100.0]
gamma: [0.001, 100.0]