colsample_bytree: [0.3, 1.0]
colsample_bylevel: [0.3, 1.0]
colsample_bynode: [0.3, 1.0]
learning_rate: [1e-5, 1.0]
max_depth: [3, 15]
n_estimators: [100, 400]
subsample: [0.3, 1.0]
min_child_weight: [2.0, 20.0]
reg_alpha: [0.001, 100.0]
reg_lambda: [0.001, 100.0]
gamma: [0.001, 100.0]
max_df: [0.5, 1.0]
min_df: [5, 15]
ngrams: [1, 3]